	<img src="images/rio-above.jpg" /> 
	<img src="images/rio_athens1.jpg" /> 
	<img src="images/pedestrian.jpg" /> 
	<img src="images/lobby3.jpg" /> 
	<img src="images/exte.jpg" /> 
	<img src="images/bar2.jpg" /> 
	<img src="images/chairs-4.jpg" />  
	<img src="images/rion.jpg" /> 
	<img src="images/anfas ktirio.jpg" /> 
	<img src="images/beds.jpg" /> 
	<img src="images/rio-night.jpg" /> 
	<img src="images/view.jpg" /> 
    <img src="images/balcony view2.jpg" /> 
    <img src="images/bat bottles.jpg" /> 
    <img src="images/cafe.jpg" /> 
    <img src="images/bar.jpg" /> 
    <img src="images/chair.jpg" /> 
    <img src="images/chairs.jpg" /> 
    <img src="images/extern.jpg" /> 
    <img src="images/fountane view.jpg" /> 
    <img src="images/fountane.jpg" /> 
    <img src="images/lobby1.jpg" /> 
    <img src="images/lobby2.jpg" /> 
    <img src="images/pedestrian-restaurant.jpg" /> 
    <img src="images/quad triple.jpg" /> 
    <img src="images/quad.jpg" /> 
    <img src="images/quad2.jpg" /> 
    <img src="images/rio bar.jpg" /> 
    <img src="images/bar3.jpg" /> 
    <img src="images/side.jpg" /> 
    <img src="images/booking_1.jpg" /> 
    <img src="images/booking_2.jpg" /> 
    <img src="images/booking_3.jpg" /> 
    <img src="images/booking_4.jpg" /> 
    <img src="images/booking_5.jpg" /> 
    <img src="images/booking_6.jpg" /> 
    <img src="images/booking_7.jpg" /> 
    <img src="images/booking_8.jpg" /> 
    <img src="images/front.jpg" /> 
    <img src="images/chairs-2.jpg" /> 
    <img src="images/chairs-out.jpg" /> 
    <img src="images/one-bed.jpg" />
    <img src="images/chairs-3.jpg" />  
    <img src="images/restaurand.jpg" />  
    <img src="images/hotel-rio-sidewalk-cafe.jpg" />  
    <img src="images/rest1.jpg" /> 
    <img src="images/flowers1.png" /> 
    <img src="images/flowers2.png" /> 