	<img src="images/rio_athens1.jpg" /> 
	<img src="images/pedestrian.jpg" /> 
	<img src="images/lobby3.jpg" /> 
	<img src="images/exte.jpg" /> 
	<img src="images/bar2.jpg" /> 
	<img src="images/rion.jpg" /> 
	<img src="images/anfas ktirio.jpg" /> 
	<img src="images/beds.jpg" /> 
	<img src="images/rio-night.jpg" /> 
	<img src="images/view.jpg" /> 
    <img src="images/balcony view2.jpg" /> 
    <img src="images/bat bottles.jpg" /> 
    <img src="images/cafe.jpg" /> 
    <img src="images/bar.jpg" /> 
    <img src="images/chair.jpg" /> 
    <img src="images/chairs.jpg" /> 
    <img src="images/extern.jpg" /> 
    <img src="images/fountane view.jpg" /> 
    <img src="images/fountane.jpg" /> 
    <img src="images/lobby1.jpg" /> 
    <img src="images/lobby2.jpg" /> 
    <img src="images/pedestrian restaurant.jpg" /> 
    <img src="images/quad triple.jpg" /> 
    <img src="images/quad.jpg" /> 
    <img src="images/quad2.jpg" /> 
    <img src="images/rio bar.jpg" /> 
    <img src="images/shower.jpg" /> 